services:
    container_name: metrics-api.local.com
    image: esumit/metric-apis:latest
    environment:
          - SERVER_PORT=9000
          - SERVER_IP_ADDRESS=0.0.0.0
          - HTTP_WRITE_TIMEOUT=15
          - HTTP_READ_TIMEOUT=15
          - HTTP_IDLE_TIMEOUT=60
          - COLLECTION_TIMEOUT=200

    ports:
      - '9000:9000'



